import React, { useState } from 'react'
import { Pencil, Plus, X } from 'lucide-react'
import { formatCurrency } from '../data'

export function BudgetsView({ budgets, transactions, onAdd, onEdit, onDelete, onNotice }) {
  const [showForm, setShowForm] = useState(false)
  const [editingBudget, setEditingBudget] = useState(null)
  const categoryOptions = [...new Set([...transactions.filter((transaction) => transaction.type === 'expense').map((transaction) => transaction.category), ...budgets.map((budget) => budget.name)])]
  const budgetsWithSpending = budgets.map((budget) => ({ ...budget, spent: transactions.filter((transaction) => transaction.type === 'expense' && transaction.category.toLowerCase() === budget.name.toLowerCase()).reduce((sum, transaction) => sum + Math.abs(transaction.amount), 0) }))
  const totalLimit = budgetsWithSpending.reduce((sum, budget) => sum + budget.limit, 0)
  const totalSpent = budgetsWithSpending.reduce((sum, budget) => sum + budget.spent, 0)
  function submitBudget(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const budget = { id: editingBudget?.id || Date.now(), name: form.get('name'), limit: Number(form.get('limit')), spent: 0, color: editingBudget?.color || 'mint' }; editingBudget ? onEdit(budget) : onAdd(budget); event.currentTarget.reset(); setShowForm(false); setEditingBudget(null) }
  return <><section className="budget-summary"><div><span>Total budget</span><strong>{formatCurrency(totalLimit)}</strong><small>Monthly allocation</small></div><div><span>Used this month</span><strong>{formatCurrency(totalSpent)}</strong><small>{totalLimit ? Math.round((totalSpent / totalLimit) * 100) : 0}% of total budget</small></div><div><span>Remaining</span><strong className="positive">{formatCurrency(totalLimit - totalSpent)}</strong><small>Available to spend</small></div></section><section className="panel budget-panel"><div className="panel-heading"><div><h2>Monthly budgets</h2><p>Spending is calculated from matching expense transactions.</p></div><button className="primary-button" onClick={() => { setEditingBudget(null); setShowForm((current) => !current) }}><Plus size={16} /> New budget</button></div>{showForm && <form className="budget-form" onSubmit={submitBudget}><label>Category<select name="name" defaultValue={editingBudget?.name || categoryOptions[0] || ''} required>{categoryOptions.length ? categoryOptions.map((category) => <option value={category} key={category}>{category}</option>) : <option value="" disabled>No expense categories yet</option>}</select></label><label>Monthly limit<input name="limit" type="number" min="1" defaultValue={editingBudget?.limit || ''} placeholder="1500000" required /></label><button className="primary-button" type="submit">{editingBudget ? 'Save changes' : 'Create budget'}</button></form>}<div className="budget-list">{budgetsWithSpending.map((budget) => { const percentage = Math.min(Math.round((budget.spent / budget.limit) * 100), 100); return <article className="budget-row" key={budget.id}><div className={`budget-icon ${budget.color}`}>{budget.name.slice(0, 1)}</div><div className="budget-info"><div><strong>{budget.name}</strong><span>{formatCurrency(budget.spent)} of {formatCurrency(budget.limit)}</span></div><div className="progress-track"><i className={percentage >= 85 ? 'warning' : ''} style={{ width: `${percentage}%` }} /></div><small>{percentage}% used</small></div><div className="budget-actions"><button className="more-button" onClick={() => { setEditingBudget(budget); setShowForm(true) }} aria-label={`Edit ${budget.name} budget`}><Pencil size={15} /></button><button className="more-button danger" onClick={() => { onDelete(budget.id); onNotice(`${budget.name} budget removed`) }} aria-label={`Remove ${budget.name} budget`}><X size={16} /></button></div></article> })}</div></section></>
}
