import React, { useState } from 'react'
import { CircleHelp, ChevronDown, Search, Settings, Target, Wallet } from 'lucide-react'
import { helpArticles } from '../data'

export function HelpCenterView({ onNotice }) {
  const [query, setQuery] = useState('')
  const articles = helpArticles.filter((article) => `${article.title} ${article.text}`.toLowerCase().includes(query.toLowerCase()))
  return <section className="help-layout"><article className="help-hero"><div><p className="eyebrow">Support center</p><h2>How can we help?</h2><p>Find quick answers about managing your money with Finora.</p></div><div className="help-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search for an answer" /></div></article><div className="help-categories"><button onClick={() => setQuery('transaction')}><Wallet size={18} /><strong>Transactions</strong><span>Manage your activity</span></button><button onClick={() => setQuery('budget')}><Target size={18} /><strong>Budgets</strong><span>Plan your monthly limits</span></button><button onClick={() => onNotice('Account support selected')}><Settings size={18} /><strong>Account</strong><span>Profile and preferences</span></button></div><article className="panel faq-panel"><div className="panel-heading"><div><h2>Popular questions</h2><p>Helpful answers for your everyday workflow.</p></div><span className="settings-badge">{articles.length} articles</span></div><div className="faq-list">{articles.length ? articles.map((article) => <details key={article.title}><summary>{article.title}<ChevronDown size={15} /></summary><p>{article.text}</p></details>) : <div className="empty-state">No help articles match your search.</div>}</div></article><article className="contact-support"><div><strong>Still need a hand?</strong><span>Our support team is happy to help you.</span></div><button className="primary-button" onClick={() => onNotice('Support request started')}><CircleHelp size={16} /> Contact support</button></article></section>
}
