import React, { useState } from 'react'
import { Bell, Settings } from 'lucide-react'

export function SettingsView({ onNotice, userEmail, userName }) {
  const [preferences, setPreferences] = useState({ notifications: true, weeklySummary: true, compactMode: false })
  const [currency, setCurrency] = useState('IDR')
  function togglePreference(key) { setPreferences((current) => ({ ...current, [key]: !current[key] })) }
  return <section className="settings-layout"><article className="panel settings-panel"><div className="panel-heading"><div><h2>Account preferences</h2><p>Choose how Finora works for you.</p></div><span className="settings-badge">Personal</span></div><div className="settings-profile"><div className="avatar">{userName.slice(0, 2).toUpperCase()}</div><div><strong>{userName}</strong><span>{userEmail}</span></div><button className="text-button" onClick={() => onNotice('Profile editing is coming soon')}>Edit profile</button></div><div className="settings-field"><label>Default currency<select value={currency} onChange={(event) => setCurrency(event.target.value)}><option value="IDR">Indonesian Rupiah (IDR)</option><option value="USD">US Dollar (USD)</option><option value="SGD">Singapore Dollar (SGD)</option></select></label></div></article><article className="panel settings-panel"><div className="panel-heading"><div><h2>Notifications</h2><p>Stay informed without the noise.</p></div><Bell size={18} color="var(--blue)" /></div><div className="preference-list">{[['notifications', 'Push notifications', 'Get alerts when a transaction is added.'], ['weeklySummary', 'Weekly summary', 'Receive a weekly snapshot of your spending.'], ['compactMode', 'Compact mode', 'Fit more information on your screen.']].map(([key, title, description]) => <label className="preference-row" key={key}><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={preferences[key]} onChange={() => togglePreference(key)} /></label>)}</div></article><button className="primary-button settings-save" onClick={() => onNotice('Settings saved successfully')}><Settings size={16} /> Save preferences</button></section>
}
